#System
GET_API_VERSION_REQ     = '\x26'
GET_API_VERSION_CONF    = '\x27'

GET_APPL_VERSION_REQ    = '\x30'
GET_APPL_VERSION_CONF   = '\x31'

#Interface (USB/BT)
QIU_REGISTER_REQ        = '\x32'
QIU_REGISTER_CONF       = '\x33'

QIU_RELEASE_REQ         = '\34'
QIU_RELEASE_CONF        = '\35'

QIU_COMMAND_REJECT_CONF = '\x37'

#Protected Commands
QIU_REGISTER_RETRIGGER_REQ = '\x38'
QIU_REGISTER_RETRIGGER_CONF = '\x39'
#Power/Akku
POWER_CONTROL_REQ = '\x5A'
POWER_CONTROL_CONF = '\x5B'

GET_VOLTAGE_REQ = '\x58'
GET_VOLTAGE_CONF = '\x59'

GET_CHARGE_STATE_REQ = '\x3A'
GET_CHARGE_STATE_CONF = '\x3B'

IRLED_EXT_CONTROL_REQ  = '\x06'
IRLED_EXT_CONTROL_CONF = '\x07'
IRLED_INT_CONTROL_REQ = '\x08'
IRLED_INT_CONTROL_CONF = '\x09'

DIM_LED_REQ = '\x0A'
DIM_LED_CONF = '\x0B'

LEDBAR_CONTROL_REQ = '\x0C'
LEDBAR_CONTROL_CONF = '\x0D'

LEDBAR_RUNNING_REQ = '\x0E' # Uncomplete docu....
LEDBAR_RUNNING_CONF = '\x0F'

EARCLIP_STATE_REQ = '\x10'
EARCLIP_STATE_CONF = '\x11'

#Flash
FLASH_READ_DATA_REQ = '\x12'
FLASH_READ_DATA_CONF = '\x13'

