#System
GET_API_VERSION_REQ     = b'\x26'
GET_API_VERSION_CONF    = b'\x27'

GET_APPL_VERSION_REQ    = b'\x30'
GET_APPL_VERSION_CONF   = b'\x31'

#Interface (USB/BT)
QIU_REGISTER_REQ        = b'\x32'
QIU_REGISTER_CONF       = b'\x33'

QIU_RELEASE_REQ         = b'\x34'
QIU_RELEASE_CONF        = b'\x35'

QIU_COMMAND_REJECT_CONF = b'\x37'

#Protected Commands
QIU_REGISTER_RETRIGGER_REQ = b'\x38'
QIU_REGISTER_RETRIGGER_CONF = b'\x39'
#Power/Akku
POWER_CONTROL_REQ = b'\x5A'
POWER_CONTROL_CONF = b'\x5B'

GET_VOLTAGE_REQ = b'\x58'
GET_VOLTAGE_CONF = b'\x59'

GET_CHARGE_STATE_REQ = b'\x3A'
GET_CHARGE_STATE_CONF = b'\x3B'

IRLED_EXT_CONTROL_REQ  = b'\x06'
IRLED_EXT_CONTROL_CONF = b'\x07'
IRLED_INT_CONTROL_REQ = b'\x08'
IRLED_INT_CONTROL_CONF = b'\x09'

DIM_LED_REQ = b'\x0A'
DIM_LED_CONF =b'\x0B'

LEDBAR_CONTROL_REQ = b'\x0C'
LEDBAR_CONTROL_CONF = b'\x0D'

LEDBAR_RUNNING_REQ = b'\x0E' # Uncomplete docu....
LEDBAR_RUNNING_CONF = b'\x0F'

EARCLIP_STATE_REQ = b'\x10'
EARCLIP_STATE_CONF = b'\x11'

#Flash
FLASH_READ_DATA_REQ = b'\x12'
FLASH_READ_DATA_CONF = b'\x13'
FLASH_WRITE_DATA_REQ = b'\x14'
FLASH_WRITE_DATA_CONF = b'\x15'
FLASH_ERASE_SECTOR_REQ = b'\x16'
FLASH_ERASE_SECTOR_CONF = b'\x17'

# Measurement/Parameters
# Start/Stop measurement
PULSE_MEAS_CONTROL_REQ = b'\x1A'
PULSE_MEAS_CONTROL_CONF = b'\x1B'
# Receive 16 Messwerte
PULSE_MEAS_DATA_16_IND = b'\x1D'
# Request breathing rate
GET_RESP_RATE_REQ = b'\x1E'
GET_RESP_RATE_CONF = b'\x1F'
# Set breathing rate
SET_RESP_RATE_REQ = b'\x20'
SET_RESP_RATE_CONF = b'\x21'
# Get gain
GET_GAIN_REQ = b'\x22'
GET_GAIN_CONF = b'\x23'
# Set gain
SET_GAIN_REQ = b'\x24'
SET_GAIN_CONF = b'\x25'

# System
# Get date time
GET_DATETIME_REQ = b'\x28'
GET_DATETIME_CONF = b'\x29'
# Set date time
SET_DATETIME_REQ = b'\x2A'
SET_DATETIME_CONF = b'\x2B'
# Prepare firmware update
PREPARE_FW_UPDATE_APPL_REQ = b'\x3C'
PREPARE_FW_UPDATE_APPL_CONF = b'\x3D'
PREPARE_FW_UPDATE_SYSTEM_REQ = b'\x3E'
PREPARE_FW_UPDATE_SYSTEM_CONF = b'\x3F'

# HMI
# Play Sound
PLAY_SOUND_REQ = b'\x2C'
PLAY_SOUND_CONF = b'\x2D'
# Push button state
PUSHBUTTON_STATE_REQ = b'\x54'
PUSHBUTTON_STATE_CONF = b'\x55'
# Accelerator state
GET_ACCEL_RAW_REQ = b'\x56'
GET_ACCEL_RAW_CONF = b'\x57'

# Status/Events/Notifications
GET_EVENTSTATUS_VECTOR_REQ = b'\x2E'
GET_EVENTSTATUS_VECTOR_CONF = b'\x2F'

# System Status Vector
GET_SYSTEM_STATUS_REQ = b'\x48'
GET_SYSTEM_STATUS_CONF = b'\x49'

#Reserved Events Teletronic
# There are 16 Samples in Measurement queue available...
PULSE_MEAS_16_TIMER_IND = b'\xD1'


