# Form implementation generated from reading ui file 'designer_qiu_qiu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Quip_test(object):
    def setupUi(self, Quip_test):
        Quip_test.setObjectName("Quip_test")
        Quip_test.resize(1131, 769)
        self.centralwidget = QtWidgets.QWidget(parent=Quip_test)
        self.centralwidget.setObjectName("centralwidget")
        self.connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(30, 40, 80, 25))
        self.connect.setObjectName("connect")
        self.app_version = QtWidgets.QPushButton(parent=self.centralwidget)
        self.app_version.setGeometry(QtCore.QRect(30, 80, 80, 25))
        self.app_version.setObjectName("app_version")
        self.api_version = QtWidgets.QPushButton(parent=self.centralwidget)
        self.api_version.setGeometry(QtCore.QRect(30, 120, 80, 25))
        self.api_version.setObjectName("api_version")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 40, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 80, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 120, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.main_operations = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_operations.setGeometry(QtCore.QRect(19, 20, 231, 171))
        self.main_operations.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.main_operations.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.main_operations.setObjectName("main_operations")
        self.retrigger = QtWidgets.QCheckBox(parent=self.main_operations)
        self.retrigger.setGeometry(QtCore.QRect(10, 140, 111, 23))
        self.retrigger.setObjectName("retrigger")
        self.retrigger_sec = QtWidgets.QSpinBox(parent=self.main_operations)
        self.retrigger_sec.setGeometry(QtCore.QRect(130, 140, 42, 26))
        self.retrigger_sec.setMaximum(20)
        self.retrigger_sec.setObjectName("retrigger_sec")
        self.label = QtWidgets.QLabel(parent=self.main_operations)
        self.label.setGeometry(QtCore.QRect(180, 140, 54, 21))
        self.label.setObjectName("label")
        self.main_operations.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.connect.raise_()
        self.app_version.raise_()
        self.api_version.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        Quip_test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Quip_test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 22))
        self.menubar.setObjectName("menubar")
        self.menuQiuGui = QtWidgets.QMenu(parent=self.menubar)
        self.menuQiuGui.setObjectName("menuQiuGui")
        Quip_test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Quip_test)
        self.statusbar.setObjectName("statusbar")
        Quip_test.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuQiuGui.menuAction())

        self.retranslateUi(Quip_test)
        QtCore.QMetaObject.connectSlotsByName(Quip_test)

    def retranslateUi(self, Quip_test):
        _translate = QtCore.QCoreApplication.translate
        Quip_test.setWindowTitle(_translate("Quip_test", "Qiu+ Hardware Test"))
        self.connect.setText(_translate("Quip_test", "Connect"))
        self.app_version.setText(_translate("Quip_test", "App Version"))
        self.api_version.setText(_translate("Quip_test", "API Version"))
        self.retrigger.setText(_translate("Quip_test", "Retrigger Mode"))
        self.label.setText(_translate("Quip_test", "Sec."))
        self.menuQiuGui.setTitle(_translate("Quip_test", "QiuGui"))
