QP_API_UNDEFINED_VOLTAGE      =  0
QP_API_ACCU_VOLTAGE           =  1
QP_API_USB_VOLTAGE            =  2
QP_API_DIG_SUPPLY_VOLTAGE     =  3
QP_API_LED_SUPPLY_VOLTAGE     =  4
QP_API_ANALOG_SUPPLY_VOLTAGE  =  5
QP_API_CC1DC_VOLTAGE          =  6
